// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: messages/laptop_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Laptop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cpu   *CPU   `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpus  []*GPU `protobuf:"bytes,4,rep,name=gpus,proto3" json:"gpus,omitempty"`
	// Types that are assignable to Weight:
	//
	//	*Laptop_WightKg
	//	*Laptop_WeightLb
	Weight isLaptop_Weight `protobuf_oneof:"weight"`
}

func (x *Laptop) Reset() {
	*x = Laptop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_laptop_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Laptop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Laptop) ProtoMessage() {}

func (x *Laptop) ProtoReflect() protoreflect.Message {
	mi := &file_messages_laptop_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Laptop.ProtoReflect.Descriptor instead.
func (*Laptop) Descriptor() ([]byte, []int) {
	return file_messages_laptop_message_proto_rawDescGZIP(), []int{0}
}

func (x *Laptop) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Laptop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Laptop) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Laptop) GetGpus() []*GPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (m *Laptop) GetWeight() isLaptop_Weight {
	if m != nil {
		return m.Weight
	}
	return nil
}

func (x *Laptop) GetWightKg() int32 {
	if x, ok := x.GetWeight().(*Laptop_WightKg); ok {
		return x.WightKg
	}
	return 0
}

func (x *Laptop) GetWeightLb() int32 {
	if x, ok := x.GetWeight().(*Laptop_WeightLb); ok {
		return x.WeightLb
	}
	return 0
}

type isLaptop_Weight interface {
	isLaptop_Weight()
}

type Laptop_WightKg struct {
	WightKg int32 `protobuf:"varint,5,opt,name=wight_kg,json=wightKg,proto3,oneof"`
}

type Laptop_WeightLb struct {
	WeightLb int32 `protobuf:"varint,6,opt,name=weight_lb,json=weightLb,proto3,oneof"`
}

func (*Laptop_WightKg) isLaptop_Weight() {}

func (*Laptop_WeightLb) isLaptop_Weight() {}

var File_messages_laptop_message_proto protoreflect.FileDescriptor

var file_messages_laptop_message_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6c, 0x61, 0x70, 0x74, 0x6f,
	0x70, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x6c, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x1a, 0x20, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x06, 0x4c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72,
	0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x50, 0x55, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12,
	0x28, 0x0a, 0x04, 0x67, 0x70, 0x75, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6c, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x50, 0x55, 0x52, 0x04, 0x67, 0x70, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x08, 0x77, 0x69, 0x67,
	0x68, 0x74, 0x5f, 0x6b, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x07, 0x77,
	0x69, 0x67, 0x68, 0x74, 0x4b, 0x67, 0x12, 0x1d, 0x0a, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x6c, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x4c, 0x62, 0x42, 0x08, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42,
	0x10, 0x5a, 0x0e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_laptop_message_proto_rawDescOnce sync.Once
	file_messages_laptop_message_proto_rawDescData = file_messages_laptop_message_proto_rawDesc
)

func file_messages_laptop_message_proto_rawDescGZIP() []byte {
	file_messages_laptop_message_proto_rawDescOnce.Do(func() {
		file_messages_laptop_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_laptop_message_proto_rawDescData)
	})
	return file_messages_laptop_message_proto_rawDescData
}

var file_messages_laptop_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_messages_laptop_message_proto_goTypes = []interface{}{
	(*Laptop)(nil), // 0: laptostore.grpc.Laptop
	(*CPU)(nil),    // 1: laptostore.grpc.CPU
	(*GPU)(nil),    // 2: laptostore.grpc.GPU
}
var file_messages_laptop_message_proto_depIdxs = []int32{
	1, // 0: laptostore.grpc.Laptop.cpu:type_name -> laptostore.grpc.CPU
	2, // 1: laptostore.grpc.Laptop.gpus:type_name -> laptostore.grpc.GPU
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messages_laptop_message_proto_init() }
func file_messages_laptop_message_proto_init() {
	if File_messages_laptop_message_proto != nil {
		return
	}
	file_messages_processor_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_messages_laptop_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Laptop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_laptop_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Laptop_WightKg)(nil),
		(*Laptop_WeightLb)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_laptop_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_laptop_message_proto_goTypes,
		DependencyIndexes: file_messages_laptop_message_proto_depIdxs,
		MessageInfos:      file_messages_laptop_message_proto_msgTypes,
	}.Build()
	File_messages_laptop_message_proto = out.File
	file_messages_laptop_message_proto_rawDesc = nil
	file_messages_laptop_message_proto_goTypes = nil
	file_messages_laptop_message_proto_depIdxs = nil
}
